apiVersion: environment.azuredevops.crossplane.io/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: environment/v1alpha1/environment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Example Environment
    projectId: ${azuredevops_project.example.id}

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: environment/v1alpha1/environment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
